#!/usr/bin/env python3
from __future__ import annotations
import calendar,csv,glob,hashlib,io,json,math,statistics,urllib.request,zipfile
from datetime import datetime,timezone
from pathlib import Path
import numpy as np

EXPECTED_FLOW_SHA="9f711752b6d9809aadc9d96532b778ce6b07f1b4b3c9ba456174fea086a5e888"
EXPECTED_TRIGGERS=89
MONTHS=[f"2023-{m:02d}" for m in range(5,13)]
START=int(datetime(2023,5,1,tzinfo=timezone.utc).timestamp())
END=int(datetime(2024,1,1,tzinfo=timezone.utc).timestamp())
HOURS=list(range(START,END,3600))
OUT=Path("artifacts/discovery")
OUT.mkdir(parents=True,exist_ok=True)

def get(url):
    req=urllib.request.Request(url,headers={"User-Agent":"CryptoLab-CCLM-002-Discovery/0.1"})
    with urllib.request.urlopen(req,timeout=120) as r:return r.read()

def independent_triggers(vals):
    out=[];last=None
    for i,v in enumerate(vals):
        lo=max(0,i-720);w=vals[lo:i]
        if len(w)<672:continue
        med=statistics.median(w)
        mad=statistics.median(abs(x-med) for x in w)
        if mad==0:continue
        z=(v-med)/(1.4826*mad)
        if abs(z)>=3.0:
            if last is None or i-last>6:
                out.append((i,float(z)));last=i
    return out

# Rehydrate only source-only artifacts generated by the already-passing viability gate.
files=sorted(glob.glob("artifacts/flow_months/*.json"))
months={}
events=0
flow={h:0 for h in HOURS}
for p in files:
    r=json.load(open(p))
    m=r.get("window_month")
    if m not in MONTHS:continue
    if r.get("classification")!="DISCOVERY_FLOW_MONTH_SOURCE_PASS":
        raise SystemExit(f"FLOW_MONTH_NOT_PASS:{m}:{r.get('classification')}")
    months[m]=r
    for route in r.get("routes",[]):
        for ev in route.get("canonical_events",[]):
            ts=int(ev["settled_ts_s"]);h=(ts//3600)*3600
            if h not in flow:raise SystemExit(f"FLOW_EVENT_OUTSIDE_DISCOVERY:{m}:{ts}")
            flow[h]+=int(ev["signed_amount_atomic"]);events+=1
if sorted(months)!=MONTHS:raise SystemExit(f"FLOW_MONTH_SET_MISMATCH:{sorted(months)}")

flow_vals=[flow[h] for h in HOURS]
payload="\n".join(f"{h}:{flow[h]}" for h in HOURS).encode()
flow_sha=hashlib.sha256(payload).hexdigest()
if flow_sha!=EXPECTED_FLOW_SHA:raise SystemExit(f"FLOW_SHA_MISMATCH:{flow_sha}")
trigs=independent_triggers(flow_vals)
if len(trigs)!=EXPECTED_TRIGGERS:raise SystemExit(f"TRIGGER_COUNT_MISMATCH:{len(trigs)}")

# Open Discovery target data only after flow/source identity is proven.
BASE="https://data.binance.vision/data/spot/monthly/klines"
prices={s:{} for s in ("AVAXUSDT","BTCUSDT")}
archive_receipts=[]
for month in MONTHS:
    y,m=map(int,month.split("-"))
    n=calendar.monthrange(y,m)[1]*24
    month_start=int(datetime(y,m,1,tzinfo=timezone.utc).timestamp()*1000)
    if m==12: next_start=int(datetime(y+1,1,1,tzinfo=timezone.utc).timestamp()*1000)
    else: next_start=int(datetime(y,m+1,1,tzinfo=timezone.utc).timestamp()*1000)
    for sym in ("AVAXUSDT","BTCUSDT"):
        name=f"{sym}-1h-{month}.zip";url=f"{BASE}/{sym}/1h/{name}"
        raw=get(url);chk=get(url+".CHECKSUM").decode().strip().split()[0].lower();sha=hashlib.sha256(raw).hexdigest()
        if sha!=chk:raise SystemExit(f"CHECKSUM_FAIL:{sym}:{month}")
        z=zipfile.ZipFile(io.BytesIO(raw));csvname=f"{sym}-1h-{month}.csv"
        if z.namelist()!=[csvname]:raise SystemExit(f"MEMBER_FAIL:{sym}:{month}:{z.namelist()}")
        parsed=list(csv.reader(io.StringIO(z.read(csvname).decode())))
        data=[r for r in parsed if r and r[0].isdigit()]
        opens=[int(r[0]) for r in data]
        if len(data)!=n or opens[0]!=month_start or opens[-1]!=next_start-3600000 or any(b-a!=3600000 for a,b in zip(opens,opens[1:])):
            raise SystemExit(f"HOURLY_INTEGRITY_FAIL:{sym}:{month}")
        for r in data:
            # Close timestamp is end of the kline's UTC hour.
            prices[sym][int(r[0])+3600000]=float(r[4])
        archive_receipts.append({"symbol":sym,"month":month,"rows":len(data),"zip_sha256":sha,"checksum_pass":True})

if len(prices["AVAXUSDT"])!=len(HOURS) or len(prices["BTCUSDT"])!=len(HOURS):
    # Includes close at 2024-01-01 00:00 and excludes May-01 00:00; count still equals 5880.
    raise SystemExit("PRICE_CLOSE_COUNT_FAIL")
if set(prices["AVAXUSDT"])!=set(prices["BTCUSDT"]):raise SystemExit("PRICE_TIMESTAMP_SET_MISMATCH")

# Build target arrays by trigger-hour index. NaN means partition-boundary ineligible.
rets={h:[float("nan")]*len(HOURS) for h in (1,4,12,24)}
for i,h0 in enumerate(HOURS):
    entry=(h0+3600)*1000
    for H in (1,4,12,24):
        exit_ts=entry+H*3600000
        if entry>=END*1000 or exit_ts>=END*1000:continue
        try:
            a0=prices["AVAXUSDT"][entry];a1=prices["AVAXUSDT"][exit_ts]
            b0=prices["BTCUSDT"][entry];b1=prices["BTCUSDT"][exit_ts]
        except KeyError:continue
        rets[H][i]=math.log(a1/a0)-math.log(b1/b0)

def signed_stats(H):
    xs=[]
    for i,z in trigs:
        r=rets[H][i]
        if math.isfinite(r):xs.append((1 if z>0 else -1)*r)
    return {"eligible_trigger_count":len(xs),"mean_signed_log_return":sum(xs)/len(xs) if xs else None,
            "median_signed_log_return":statistics.median(xs) if xs else None}

observed={str(H):signed_stats(H) for H in (1,4,12,24)}
if observed["4"]["eligible_trigger_count"]<30:raise SystemExit("PRIMARY_ELIGIBLE_SAMPLE_BELOW_30")

# Exact PCG64 offsets, permutation-major then month-major.
rng=np.random.Generator(np.random.PCG64(20260924))
month_lens=[calendar.monthrange(2023,m)[1]*24 for m in range(5,13)]
offsets=np.empty((10000,8),dtype=np.int32)
for p in range(10000):
    for j,n in enumerate(month_lens):
        offsets[p,j]=rng.integers(48,n-48+1)

np.savetxt(OUT/"flow.txt",np.asarray(flow_vals,dtype=np.int64),fmt="%d")
np.savetxt(OUT/"relret4.txt",np.asarray(rets[4],dtype=np.float64),fmt="%.17g")
np.savetxt(OUT/"offsets.csv",offsets,fmt="%d",delimiter=",")

receipt={
 "lab_id":"CROSSCHAIN-LIQUIDITY-MIGRATION-001","child_id":"CCLM-CCTP-SETTLED-FLOW-002",
 "stage":"DISCOVERY_INPUT_AND_OBSERVED_V0.1","captured_at_utc":datetime.now(timezone.utc).isoformat(),
 "discovery_period":"2023-05-01..2023-12-31","flow_sha256":flow_sha,
 "canonical_settled_events":events,"independent_trigger_count":len(trigs),
 "positive_triggers":sum(z>0 for _,z in trigs),"negative_triggers":sum(z<0 for _,z in trigs),
 "first_trigger_utc":datetime.fromtimestamp(HOURS[trigs[0][0]],tz=timezone.utc).isoformat(),
 "last_trigger_utc":datetime.fromtimestamp(HOURS[trigs[-1][0]],tz=timezone.utc).isoformat(),
 "observed":observed,"binance_archives":archive_receipts,
 "offset_rng":"numpy.Generator(PCG64(seed=20260924))","offset_shape":[10000,8],
 "offset_rotation":"np.roll(month_flow,+k)",
 "oos_opened":False,"holdout_opened":False,"pnl_opened":False,"mutation":False
}
(OUT/"observed_receipt.json").write_text(json.dumps(receipt,indent=2,sort_keys=True)+"\n")
print(json.dumps(receipt,indent=2))
